server:
  servlet:
    session:
      cookie:
        name: SCIM_SERVER_MGMT_SESSION

spring:
  application:
    name: scim-server-mgmt
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/common
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: ${AUTH0_REDIRECT_URI}
        provider:
          auth0:
            issuer-uri: ${AUTH0_ISSUER_URI}

logging:
  level:
    "[de.palsoftware.scim]": DEBUG
    "[org.springframework.security]": WARN

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    ping:
      enabled: false
    ssl:
      enabled: false
    diskspace:
      enabled: false


app:
  security:
    actuator:
      api-key: ${ACTUATOR_API_KEY}
    oidc:
      role-claim: ${APP_SECURITY_OIDC_ROLE_CLAIM:https://scimplayground.dev/roles}
      admin-role: ${APP_SECURITY_OIDC_ADMIN_ROLE:admin}
      user-role: ${APP_SECURITY_OIDC_USER_ROLE:user}

  scim-api:
    base:
      url: ${APP_SCIM_API_BASE_URL:http://localhost:8080}