apiVersion: v1
kind: Secret
metadata:
    name: scim-postgres-superuser
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:RpP3Q+sju98=,iv:T/g4El6MGOhlVANGPFvMfeZSmSUmm0YTDZARlif1HRA=,tag:2fXRky8P7kODOWldiuttqQ==,type:str]
    password: ENC[AES256_GCM,data:SGXVmF/IMZOBFZ/VBNt0gyx160kKfSpi,iv:Z71afVjFpW2Lm29WmeH8L77FyWQ3RtJcFqQbP/d4G5c=,tag:O2a08G8tMobJ6m7fHEWRTg==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeWc0Ym5SMUgrQXRxdFdu
            OWtBK2UxYzVvUG1jajlsT1FadERMUHFHWWpvCm0ralpWTHRKNWpvVk16dkIzQjZT
            YjlUaHBML1p6RHRrQ0RUSFNIWjFUQkUKLS0tIFg0Z20veitsdkc0SkxleFE4bFFh
            TC9VZ0lrQWVLZEF6UGNURHAwSFdKVDAKEN1fzcFkwE1AEhBQPINVmTC8ZuwcSOAt
            RDjfKMA3Tjnf4I1jjeuPdJGP1kviefiq6hsZlhvXfhi123Itgju3Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T14:28:34Z"
    mac: ENC[AES256_GCM,data:ixVk4pKBzQ8QgCMB8QDa7F55gxKo7HFPHvWU27bd2wLsdk12geR7u6tqvqcFQnhrbr+4gbuyTK43/kgr3xvzhi2m5Dn58T2ugR5NoRBApd6O3sAv55reeklVofkh3LMzmCEWs6kydmEW4RSJYOsBglpyLxVWc995/E2Yi8+0+Gc=,iv:ZWjPe5+UR8E52YouNBXEhVqJgpEPxXbecO9CrIGTE2I=,tag:LL4JVeEPw06VG2KMXG/h4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
