apiVersion: v1
kind: Secret
metadata:
    name: scim-postgres-validator
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:RRhOPM4AwpJYBYMhUBo=,iv:skmebd/VxWfE5/CF8Q/JtWTHE9do9gh+XaReuXSuOm8=,tag:yn3+t6lMA3+YWjk/tardxA==,type:str]
    password: ENC[AES256_GCM,data:W8FlVgd8QGrc3dJNMhSAA9qSVjOLWt4z,iv:FNGOQMQQk+c6+IKZXpOXB+7iBPz5THb16w8SfY2J1b8=,tag:GMdR4vyNqrQLX0L6aYVe4g==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOGsvSzVtaXJqSGtSY3hv
            Q0VJV09rZzdDTkpmMVZiSEFoRFIrSUFVL0RRCmhkZnpaUGkrY0J2ZlVvVmF6VjdB
            VGE2emg5dHRaN3NJcHdIT3BYRTZVZVEKLS0tIEJXZTRiazM3VTFDVVV6bDFDcXha
            ZFcwVHhzUm92Q3psQXR2WjBiWC9oVW8KRPK/RJiFoh76BJCvnJGCdtPS6CKXy1sP
            QiulBwudI0i1xbw58gw2QZ2my0UU/6VQyqvWnZ7YftqtUar1VDfxfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T14:28:52Z"
    mac: ENC[AES256_GCM,data:I/4BXyST/uRbtzbJjqBFww0fzN9/bReKp0Ybb8eUTydVXndpE1OiLsIh2GOK/VRMzR+cL0pbNDEd7MphAbx33J8Kt3xP3itxHKGo0mSKUhUjtJpluPF0ZEte8IDbEliGvH0FQ9eZdtOf4QWcvCCQPSM12OhIyWXy4/38EWcMJH0=,iv:1A/BtIKje3MqjmTnj1B6e/PlYEvO9BAmgGW7PCXClfQ=,tag:CYvRHZ5Hm8dMbgR0ERJ25g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
