apiVersion: v1
kind: Secret
metadata:
    name: scim-postgres-playground
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0kFhe469fgwyY51Zz2lZ,iv:O9KYvo8cjGKfmA4SmAt94RKlCXwIoZxBzUS0z0vFWS0=,tag:7S4cMRtfcNgJkqIGbQYZ8g==,type:str]
    password: ENC[AES256_GCM,data:k9aU16ZFcYnzXvZsrbNVtGFcEitPV4hy,iv:PjL1J+yKsmtTsJ+d5o3yHD+xZMSk46jQwRx1+fuZBbM=,tag:Ko/CizQY+p3J+vrvfOg7Pg==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNkZ1eGNrOFI5Zi9mYVcz
            K3Zma3pCRzljRTlSSmVoU1E3VERZdktab2k0ClhiWElqZTJ6TG4ycU9DTjBaL1Zp
            L05aRFhUUDNwd1R1WmZUNE45NC84aTAKLS0tIFMwNDdqQVAxZDNlVS9aSnFjc0Iv
            S3ZYWE5Bd3UrcWE2UjMycmxNWnhDTEkKKuRerZjqbHyXK9uNMcoM/U7nA0MIgf1a
            ayqPpA9uNODmqan5dKHZwCtSTTzepGldi6kPD0QLSIPKw6Ne/ni1IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T14:28:06Z"
    mac: ENC[AES256_GCM,data:nyCALSeNO82ilx/iBdrowL2Hj+IUGPGL5sAolWoiKFBg8GzBVvPhqMzTaLp4UATu8zehHMvZDqIkfl+NL2QmbOdrJMBdRXrQO+ehZULPnd8m+EuMpWXqx32C3+MqI6yiBk22w0fn6CWzxLt3SGcTlpOlIi6n5NIkfXtyyA2oO3M=,iv:+wBfkkY/dd6WM+0uNxIE6dGmNRG0lsKmeYvGsYjUqEk=,tag:7+ZQOq8+bA+oq41VZsYkdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
