apiVersion: v1
kind: Secret
metadata:
    name: scim-server-mgmt-k3s-secrets
type: Opaque
stringData:
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:YkRIjyD9SgMLoGF21fe0,iv:1eDlmhUbOxu7PbdvQ0iDkJ+AsGyMv3QlPG1xfIDHLDE=,tag:oqTwIFmlbctQ5hFW99HTfA==,type:str]
    ACTUATOR_API_KEY: ENC[AES256_GCM,data:+zoLZ0N85buLS0aglTSdvg==,iv:NUTLfzdgOihk0T3H8fvjtbJlcdQ1/l/3OYjb/kxnv7w=,tag:Qf/06GfEAko9HQwQQ3lP4Q==,type:str]
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:ddp6MlmrTWj1ChCrefdL3rMoIuOr75wFZ6JuqG1itxHIRICH,iv:JiGxcfHGMFvqThIpczYvDVkwC1IJ4I4hRZO7UXAOUxQ=,tag:kvjNZtW2L/MuaGKoZ3MxCw==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:k9LuKBzBxGE8/fJzeU/KFZaxKr8owo2P690aE8Cr2+C6FSyOOTlGFg==,iv:7o8l7wLA4AhYVsc3w48dsRxNyDnyyWudNlDpzsCCLO4=,tag:edJGt0hWOLnaFQ7N0FLdQw==,type:str]
    AZURE_TENANT_ID: ENC[AES256_GCM,data:pYk1sI18AT9qviXfSKqL8O3KbqXTM+EcMUEI/BjbkDW7Boof,iv:ni82wW7uMNCxOmkMPl7yy04DgKDv7mjGie/UGEaBrXw=,tag:YUdlWZ2bFS+mMRSJsXgqHg==,type:str]
    AZURE_SCOPES: ENC[AES256_GCM,data:Nrx4BUz9K3D+gEzmFMyR8V9pKHQ4mTtP9TTLlrHTBrIskH9D/N7OWnUwMuUlpyb7SD57/h53pG3pY2zifg==,iv:jpo777CTVGbS9qTROD+XR0NSenMKpsh0Eokkn/z9iVA=,tag:BtzF+T9SPf5y6MhPC9089w==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQXNVVVpvdFM4WHE0YjFu
            YlVxWjBzMFprZXZCcysrVDFOTHZpY2JQbDJ3Ckx3Tk9ack1XNjNvckFTejdUTytj
            dkR6aFdCYnd2OU53T0hQdmRBRG9ld28KLS0tIDBxNTZFM0xUclpxMVVuYjg1LzVN
            T2JreVVlVEt1S3J5LzZRekVSVFY4c0kKyOV5MRLGnYyWLyzcHa9UmfItp2d/hKsX
            b2duPUECnG01v19Hxkwo/UdJD/yIYgTvHpCl2oih/plqCO3baEmIqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T19:06:38Z"
    mac: ENC[AES256_GCM,data:OkBZ/zlR1usfkC+TocEy2yXqtnnpitg8EsuVEXiBAwvRGOnl6xA+mbrd3g3Z2eilCpG1XWlPX13yAmTd2YFOLp7ryWu5Ma1hgQy44t4aFY0fsMLPWZqA9vk5WqAa9YyTAyVoGTnsKtl5IpOMlsR1AUcbZNAhenqrgG6/sxRJkYc=,iv:2zbN1+qoMBplJBB0oRIRJPOwmzk3MjSw/VIlqq/U+4k=,tag:INia+cgemsrJpVD1ZOVQEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
