apiVersion: v1
kind: Secret
metadata:
    name: scim-server-mgmt-k3s-secrets
type: Opaque
stringData:
    ACTUATOR_API_KEY: ENC[AES256_GCM,data:NBNrxcKvNgBZ6HIwWt3yWNJ55VY3qu+DecOOs7cLevU=,iv:tIzmjAtqaFjCWg9VPgWk1eunJgLKfPG1TVTaySl5ax4=,tag:0t9JfRBln8T4q+dUapNXWQ==,type:str]
    AUTH0_CLIENT_ID: ENC[AES256_GCM,data:5V8zE+VVVCAd79vTloTNdBaNCTUNkx2/vmbThMMtDzk=,iv:i1dL4uaV5cBL5PTf2ZZk+ElkuFMjjJ1r/qFArbby6Tk=,tag:+swsxiuEESokN2Gq1GrgtQ==,type:str]
    AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:FM0Kz+a/9m0O1dEUBZk6jAMmoNaLfT3trFhpPPkYdxE2N93nIUfmPB2NPZoWBCD6rfG49o/m3ayEK/Xvl5FHEQ==,iv:E8KBDydU7JE0557otwODSdbuYGMTzvwLnejF47cUjqw=,tag:yEyGZl5rP9x3U6K1PtYm9A==,type:str]
    AUTH0_ISSUER_URI: ENC[AES256_GCM,data:g6dX7zTbpNKJhOzBMXEGGuiagqTdZYOKouuOKwU=,iv:XIV5LDlrVOnEf1ylpMSzfc6Cmt7LYI6UM73zrRAHXbM=,tag:0U+SQgcK+l9oDDcbF+Kqxg==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQXNVVVpvdFM4WHE0YjFu
            YlVxWjBzMFprZXZCcysrVDFOTHZpY2JQbDJ3Ckx3Tk9ack1XNjNvckFTejdUTytj
            dkR6aFdCYnd2OU53T0hQdmRBRG9ld28KLS0tIDBxNTZFM0xUclpxMVVuYjg1LzVN
            T2JreVVlVEt1S3J5LzZRekVSVFY4c0kKyOV5MRLGnYyWLyzcHa9UmfItp2d/hKsX
            b2duPUECnG01v19Hxkwo/UdJD/yIYgTvHpCl2oih/plqCO3baEmIqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T09:07:15Z"
    mac: ENC[AES256_GCM,data:ZlRh43Q039OBDIKAo79IvCdWFlxY98eGQK8FSiokC1k0/g58Fqu0BF3yQnJCcN245qmQeDkxq2K7JBqn+T6ptY5PNxXV/bSQmVGAK/KLJ8fABKFfi+xstMFUuuyiEItrzGUuwt/80Rm+WaWqHMZKL6HiTQ5mXMbO2vS9/4TCyKQ=,iv:bAGhHR3NCRzbPdXV43+w7W3cP0RFtmhCC+9sM+WF33o=,tag:/PvCGNUrGmF36tjBPNGwRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
