apiVersion: v1
kind: ConfigMap
metadata:
  name: scim-server-mgmt-k3s-config
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: jdbc:postgresql://scim-postgres-rw:5432/scimplayground
  AUTH0_REDIRECT_URI: https://ui.scimsandbox.net/login/oauth2/code/auth0
  APP_SCIM_API_BASE_URL: https://api.scimsandbox.net
  APP_SECURITY_OIDC_ROLE_CLAIM: https://scimplayground.dev/roles
  APP_SECURITY_OIDC_ADMIN_ROLE: admin
  APP_SECURITY_OIDC_USER_ROLE: user