apiVersion: v1
kind: Secret
metadata:
    name: scim-server-api-k3s-secrets
type: Opaque
stringData:
    ACTUATOR_API_KEY: ENC[AES256_GCM,data:iDcGrPXPXizvECsF4bJgHoO6cFxhYs17kJbjD7+l4ZE=,iv:k1Vm5LIgUkdy/Yoy7IGqaczPC5/d1nTDTHFnpceBrV4=,tag:Hs9HVIc0pAoZzL6qM6b4nw==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SS9UUHEzOXRBd3ZXMTVu
            dzB3VmxqZHl2cmpETXk5N0Z1Qm5uSVJ0ZUY0CjFFSFZMZnRzSlVyNzlUYUZDL2wy
            ZlFFVXNxcXpvVlRKSUhyaktCSTBHeTAKLS0tIEtVUm5JOE9sWnpKOEc0R1JTVE84
            Ui96c1VseXZrZDhXWWFwMkw2R2puQWsKWiRU7nRAerImiMlmGrtcPvr0yhHBXgPw
            NYTd6laSrAmk1lMgq9PUBsyXG0mnRLKZ7qyjt/ISGwky/UjVIbr/sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T14:13:28Z"
    mac: ENC[AES256_GCM,data:dwHstr4Q9Dp4nVKlkOXOGd8xP3ibyIeyflM5mA1+DFHyKEoPqgPy4C9DhAHGYZopps5zIvgByH2V72kxdtsNJShTQxxR7B8WOjqSA9PWU3U3ILcIq+b03o5SrZ9uuTo4wtnRSE2ClSbh/SJC0d/kEiPXpbQsVpuqffwlvgE3ySA=,iv:HRi0I4Y20c+y4CQxJHSGOlCdmCyVjoxuVWkK3S0JzH0=,tag:3D9MP7I0RJIs6wqYvWXeZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
