apiVersion: v1
kind: Secret
metadata:
    name: scim-server-api-k3s-secrets
type: Opaque
stringData:
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:umFrv2grHzQ5/Awh3MmgDpVojcDoLvl5gISm7BLbRSPCzQ==,iv:p/6zQgjTdePV4pxWsgpXbVDVA6BRfpqfL5mLTnH1Acg=,tag:TKzNjz1GC7MKxLMjAxV15A==,type:str]
    ACTUATOR_API_KEY: ENC[AES256_GCM,data:fSl1EdagBXA1O1EsWZfIk2rKMDlH/WHz5NM=,iv:jnggCOKdts0/RLN5r1wkfu2NHL7MbIUhr8RWrdOC2CI=,tag:ZGydOi+KUSZZK4vaL7v3jA==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SS9UUHEzOXRBd3ZXMTVu
            dzB3VmxqZHl2cmpETXk5N0Z1Qm5uSVJ0ZUY0CjFFSFZMZnRzSlVyNzlUYUZDL2wy
            ZlFFVXNxcXpvVlRKSUhyaktCSTBHeTAKLS0tIEtVUm5JOE9sWnpKOEc0R1JTVE84
            Ui96c1VseXZrZDhXWWFwMkw2R2puQWsKWiRU7nRAerImiMlmGrtcPvr0yhHBXgPw
            NYTd6laSrAmk1lMgq9PUBsyXG0mnRLKZ7qyjt/ISGwky/UjVIbr/sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T18:12:50Z"
    mac: ENC[AES256_GCM,data:5oco07suLZsu2q77t3i0k3dq80rOktvtI39AYyf3JoC8XDvOLvjeFeX8nyU245EiNugcJT37OSIu7B/lPHoaizKu7WPqLQvn7TaqEcwtv2iZJmfkkL7coHWcAFEPyc/yTrHTdJU3SLG7MlMkWrVmFRMtdzwyr6xWoExggE8IQVw=,iv:VYGACow3jkZYCHKt9P4oGLkZ5SO6H6Bvew2BR14Pd5s=,tag:vpTbNKElBGefiAXNIWikcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
