apiVersion: v1
kind: ConfigMap
metadata:
  name: scim-validator-mgmt-k3s-config
data:
  SERVER_PORT: "8082"
  SPRING_DATASOURCE_URL: jdbc:postgresql://scim-postgres-rw:5432/scimvalidation
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  AUTH0_REDIRECT_URI: https://val.scimsandbox.net/login/oauth2/code/auth0
  APP_SECURITY_OIDC_ROLE_CLAIM: https://scimplayground.dev/roles
  APP_SECURITY_OIDC_ADMIN_ROLE: admin
  APP_SECURITY_OIDC_USER_ROLE: user