apiVersion: v1
kind: ConfigMap
metadata:
  name: scim-validator-mgmt-k3s-config
data:
  SERVER_PORT: "8082"
  SPRING_PROFILES_ACTIVE: cloudflare
  SPRING_DATASOURCE_URL: jdbc:postgresql://scim-postgres-rw:5432/scimvalidation
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_DATASOURCE_USERNAME: scim_validator
  APP_SECURITY_CLOUDFLARE_ROLE_CLAIM: https://scimsandbox.net/roles
  APP_SECURITY_OIDC_ADMIN_ROLE: admin
  APP_SECURITY_OIDC_USER_ROLE: user
  CLOUDFLARE_ACCESS_ISSUER_URI: https://scimsandbox.cloudflareaccess.com
  CLOUDFLARE_ACCESS_AUDIENCE: 9b1ea9fac999e94d6d2522a61d4323ac8ca4f5759c2fbc73fe489a034fc51627
  CLOUDFLARE_ACCESS_JWK_SET_URI: https://scimsandbox.cloudflareaccess.com/cdn-cgi/access/certs
  CLOUDFLARE_ACCESS_LOGOUT_URL: https://scimsandbox.cloudflareaccess.com/cdn-cgi/access/logout
  CLOUDFLARE_ACCESS_TOKEN_HEADER: Cf-Access-Jwt-Assertion