apiVersion: v1
kind: Secret
metadata:
    name: scim-validator-mgmt-k3s-secrets
type: Opaque
stringData:
    ACTUATOR_API_KEY: ENC[AES256_GCM,data:3mZGKAhuYBfRTjd8odLIzw==,iv:0waDAQjwCOprQmKeRzXpVM35Hl5xxOWx8dzOyqtjMsU=,tag:ttAuVC2L1D9Vrctad9K82w==,type:str]
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:D8BUR3o0edi2BI+o+w0VQaPodn9dqOY5XeiUYJoVgrdmo7nI,iv:TgoW2GoAodCeDE+QzADtcN3QBHb/GhgSDp90RUvGjdY=,tag:7jmgtEmvWiwA0Kd2d3osag==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:gC7N54Ej81AbJMGoZ4LlOlY4HTAGspP5dH5bjxm4twUzRyCwF/ujIw==,iv:h5ID0cwjmHJYNUqHkybZgZHQ/VCva2bkqYcYJETSiV8=,tag:VU/mTCSyuWjukbi9es0j0Q==,type:str]
    AZURE_TENANT_ID: ENC[AES256_GCM,data:XrqQK31TIyi42Ximvw3EBSjQU4bLK75ps8a4jqHb5SfjoaOn,iv:xC6xPTm6YtZQaHAruQlVEHCajgkVJ7Bysnw6cWOcpUU=,tag:QP0MmktwCIGaIRpQRZb16Q==,type:str]
    AZURE_SCOPES: ENC[AES256_GCM,data:cd9cIP5bIANFMiHUb5CHKaRHwzey0RIe6dTQd0HzJ8g4y7d+tGJyQ7ANHh3pw+vA7V0ov0349FkQk0obAQ==,iv:1YjY3PJsJe+jm34IEWjQqmZjld4C5+8KNbDkvvY34gc=,tag:A4uXVB+X80crNqtHdLpuWw==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSk9qZHFxaVZ5RnpTKzhP
            QWUyWTNSZ0JMb1VOQkN0dkxndDJ5TkhGL0VVCmhyWWlCN2xlem40ZzQ2cS81aWgv
            UXA3SUQ1RmhjeVpxcDhPZ0RpR2pnTU0KLS0tIEMxWlcyVHFxOTlyOWFYUFdBWjdX
            VExGZGtXWWJXOHJkb1paZHhTRHViNXMKoJYy5PatO+SFoJy93IUkqYAt1JZlexnM
            yVmxa66O6j9J5KGmgWuCcGF4AVLGql58QZqXElX2voPY4Hg2C/LDHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T19:19:42Z"
    mac: ENC[AES256_GCM,data:GGlqzLkxsYpeGmf6u6Ib6wI3pKmpxqaG+IykLGUgjkWiWcQl3jyWf/Xm7QLPSM/58nVwtfV13u+3h6utcD4nzPGFv8+wf1bH2/ly/qE3G7C6Xd7wqqezgP643yblyY/nE5x7kHxCrQnwlZfRtKT4l+vLxp/lRmDCPjSJrgrdJQ4=,iv:ctrxJMwqh80U46tTkAN0GLQgz0Z+Lm6AGAgJ8LJsrLM=,tag:0mQpwJ89W7ls/RP4tHoH6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
