server:
  port: 8080
spring:
  application:
    name: scim-server-api
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/common
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        "[default_batch_fetch_size]": 100
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

logging:
  level:
    "[com.scimplayground]": DEBUG
    "[org.springframework.security]": WARN

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,prometheus
  health:
    ping:
      enabled: false
    ssl:
      enabled: false
    diskspace:
      enabled: false

app:
  security:
    actuator:
      api-key: ${ACTUATOR_API_KEY}
  cleanup:
    workspace:
      enabled: true
      cron: "0 0 */2 * * *"
      zone: UTC
      stale-after: P3M